"""
Improve command - Improve.
"""

import re
from pathlib import Path

import click
from rich.panel import Panel
from rich.prompt import Confirm

from lecture_forge.cli.utils import console
from lecture_forge.config import Config
from lecture_forge.slides import SlideConverter
from lecture_forge.utils import logger


def _find_image_dir_from_html(html_path: Path) -> Path:
    """Extract image directory path from HTML metadata comments."""
    try:
        with open(html_path, "r", encoding="utf-8") as f:
            html_content = f.read()

        # Look for metadata comment: <!-- image_dir: data/images/session_xxx -->
        match = re.search(r"<!-- image_dir: (.+?) -->", html_content)

        if match:
            image_dir = Path(match.group(1))
            if image_dir.exists():
                return image_dir

        # Fallback: try to infer from filename
        filename = html_path.stem
        parts = filename.rsplit("_", 2)
        if len(parts) >= 3:
            topic_part = parts[0]
            date_part = parts[1]

            # Search for matching directories
            image_base = Path(Config.DATA_DIR) / "images"
            if image_base.exists():
                for img_dir in image_base.iterdir():
                    if img_dir.is_dir() and topic_part in img_dir.name and date_part[:8] in img_dir.name:
                        return img_dir

    except Exception as e:
        logger.error(f"Failed to extract image dir from HTML: {e}")

    return None


@click.command()
@click.argument("lecture_path", type=click.Path(exists=True))
@click.option(
    "--enhance-pdf-images",
    is_flag=True,
    help="Generate descriptions for PDF images using page text (costs ~$0.04 per 400 images)",
)
@click.option("--source-pdf", type=click.Path(exists=True), help="Source PDF file (required for --enhance-pdf-images)")
@click.option("--to-slides", is_flag=True, help="Convert lecture to presentation slides format (Reveal.js)")
def improve(lecture_path: str, enhance_pdf_images: bool, source_pdf: str, to_slides: bool) -> None:
    """
    Improve existing lecture quality with optional enhancements.

    Apply post-generation improvements to enhance lecture quality:
    - Generate descriptions for PDF images using page text inference
    - Re-match images with better descriptions
    - Update HTML with additional images
    - Convert lecture to presentation slides format

    \b
    Enhancement Options:
      --enhance-pdf-images: Generate descriptions for PDF-extracted images
                            Uses GPT-4o-mini to infer image content from page text
                            Cost: ~$0.04 per 400 images (384 pages)
                            Expected improvement: +50% PDF image usage

      --to-slides:          Convert lecture HTML to Reveal.js slides
                            Creates separate slides.html file
                            Automatically splits content into slides
                            Preserves images, code, and diagrams

    \b
    Slide Keyboard Shortcuts:
      Arrow Keys / Space    - Navigate slides (→ next, ← previous, ↑↓ vertical)
      Home / End            - First / last slide
      Esc / O               - Overview mode (see all slides)
      S                     - Speaker notes (if available)
      F                     - Full screen mode
      B / .                 - Pause/blackout (blank screen)
      Alt+Click             - Zoom to clicked element
      ?                     - Show keyboard shortcuts help

    \b
    Examples:
      # Enhance PDF images with descriptions
      $ lecture-forge improve outputs/lecture.html \\
          --enhance-pdf-images \\
          --source-pdf "AI Engineering Guidebook.pdf"

    \b
      # Convert to presentation slides
      $ lecture-forge improve outputs/lecture.html --to-slides

    \b
      # Combine both enhancements
      $ lecture-forge improve outputs/lecture.html \\
          --enhance-pdf-images --source-pdf "doc.pdf" --to-slides

    \b
    Note:
      - As of v0.1.0, auto-describe is enabled by default during creation
      - This command is for legacy lectures or re-enhancement
      - HTML must be generated by lecture-forge (contains metadata)
      - Source PDF required for --enhance-pdf-images
      - Original lecture file will be backed up before modification
    """
    console.print()
    console.print(Panel.fit("[bold cyan]🔧 LectureForge - Lecture Improvement[/bold cyan]", border_style="cyan"))
    console.print()

    lecture_path = Path(lecture_path)

    if not lecture_path.exists():
        console.print(f"[red]❌ Lecture file not found: {lecture_path}[/red]")
        return

    if enhance_pdf_images:
        if not source_pdf:
            console.print("[red]❌ --source-pdf required when using --enhance-pdf-images[/red]")
            console.print("   Example: --source-pdf 'document.pdf'")
            return

        source_pdf = Path(source_pdf)
        if not source_pdf.exists():
            console.print(f"[red]❌ Source PDF not found: {source_pdf}[/red]")
            return

        # Run PDF image enhancement
        console.print("[bold]Step 1: Enhancing PDF Images[/bold]")
        console.print("━" * 50)

        # Find image directory from HTML metadata
        image_dir = _find_image_dir_from_html(lecture_path)

        if not image_dir:
            console.print("[red]❌ Could not find image directory from HTML metadata[/red]")
            console.print("   Make sure the HTML was generated by lecture-forge")
            return

        console.print(f"   PDF: {source_pdf.name}")
        console.print(f"   Images: {image_dir}")
        console.print()

        # Confirm cost
        console.print("[yellow]⚠️  This will use GPT-4o-mini API (estimated cost: $0.40)[/yellow]")
        if not Confirm.ask("   Proceed with image enhancement?", default=True):
            console.print("\n[green]✓ Cancelled[/green]")
            return

        # Run enhancement
        from lecture_forge.tools.pdf_image_describer import PDFImageDescriber

        describer = PDFImageDescriber()

        with console.status("[bold green]Generating image descriptions..."):
            result = describer.enhance_images(pdf_path=str(source_pdf), image_dir=str(image_dir))

        if not result["success"]:
            console.print(f"[red]❌ Enhancement failed: {result.get('error', 'Unknown error')}[/red]")
            return

        console.print(f"[green]✅ Enhanced {result['enhanced_count']} images[/green]")
        console.print(f"[green]💰 Actual cost: ${result['estimated_cost']:.4f}[/green]")
        console.print()

        # Step 2: Reload and re-generate HTML with new descriptions
        console.print("[bold]Step 2: Re-matching Images[/bold]")
        console.print("━" * 50)
        console.print("   This feature is coming soon!")
        console.print("   Descriptions have been saved to:")
        console.print(f"   {result['descriptions_file']}")
        console.print()
        console.print("[yellow]💡 Tip: For now, you can regenerate the lecture to use new descriptions[/yellow]")

    if to_slides:
        # Run slides conversion
        console.print("[bold]Converting to Presentation Slides[/bold]")
        console.print("━" * 50)
        console.print()

        slides_path = lecture_path.parent / f"{lecture_path.stem}_slides.html"

        # Use SlideConverter from slides module
        converter = SlideConverter(console=console)
        success = converter.convert(lecture_path, slides_path)

        if success:
            console.print(f"[green]✅ Slides created: {slides_path}[/green]")
            console.print(f"[green]   Open in browser and press 's' for speaker notes[/green]")
            console.print()
        else:
            console.print(f"[red]❌ Slides conversion failed[/red]")

    if not enhance_pdf_images and not to_slides:
        console.print("[yellow]No improvement options specified[/yellow]")
        console.print("Use --enhance-pdf-images to generate PDF image descriptions")
        console.print("Use --to-slides to convert to presentation format")


